2024-08-15 13:58:53.466 [info] Experiment 'pythonCreateEnvOnPipInstall' is active
2024-08-15 13:58:53.466 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-08-15 13:58:53.466 [info] Experiment 'pythonSurveyNotification' is active
2024-08-15 13:58:53.466 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-08-15 13:58:53.466 [info] Experiment 'pythonTestAdapter' is active
2024-08-15 13:58:53.473 [error] Reading directory to watch failed [Error: ENOENT: no such file or directory, scandir '/root/API/.pixi/envs'
	at Object.readdirSync (node:fs:1515:26)
	at /root/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/out/client/extension.js:2:586747
	at /root/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/out/client/extension.js:2:586938
	at Array.map (<anonymous>)
	at d.initWatchers (/root/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/out/client/extension.js:2:586656)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async d.ensureWatchersReady (/root/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/out/client/extension.js:2:543067)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/root/API/.pixi/envs'
}
2024-08-15 13:58:53.473 [error] Dir "/root/API/.pixi/envs" is not watchable (directory does not exist)
2024-08-15 13:58:53.641 [info] Default formatter is set to null for workspace /root/API
2024-08-15 13:58:53.644 [info] Starting Environment refresh
2024-08-15 13:58:53.644 [info] Searching for interpreters in posix paths locator
2024-08-15 13:58:53.647 [info] Searching for pyenv environments
2024-08-15 13:58:53.647 [info] Searching for conda environments
2024-08-15 13:58:53.647 [info] Searching for global virtual environments
2024-08-15 13:58:53.647 [info] Searching for custom virtual environments
2024-08-15 13:58:53.665 [info] pyenv is not installed
2024-08-15 13:58:53.665 [info] Finished searching for pyenv environments: 20 milliseconds
2024-08-15 13:58:53.665 [info] Finished searching for custom virtual envs: 20 milliseconds
2024-08-15 13:58:53.670 [info] > conda info --json
2024-08-15 13:58:53.672 [info] > pixi --version
2024-08-15 13:58:53.672 [error] [Error: spawn pixi ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:286:19)
	at onErrorNT (node:internal/child_process:484:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pixi',
  path: 'pixi',
  spawnargs: [ '--version' ]
}
2024-08-15 13:58:53.673 [info] > hatch env show --json
2024-08-15 13:58:53.673 [info] cwd: .
2024-08-15 13:58:53.675 [info] > pyenv which python
2024-08-15 13:58:53.675 [info] cwd: .
2024-08-15 13:58:53.675 [info] Finished searching for global virtual envs: 30 milliseconds
2024-08-15 13:58:53.678 [info] Found: /bin/python3 --> /bin/python3.11
2024-08-15 13:58:53.678 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-08-15 13:58:53.681 [info] Found: /usr/bin/python3 --> /usr/bin/python3.11
2024-08-15 13:58:53.681 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-08-15 13:58:53.686 [info] Found: /usr/local/bin/python --> /usr/local/bin/python3.12
2024-08-15 13:58:53.686 [info] Found: /usr/local/bin/python3 --> /usr/local/bin/python3.12
2024-08-15 13:58:53.686 [info] Found: /usr/local/bin/python3.12 --> /usr/local/bin/python3.12
2024-08-15 13:58:53.694 [info] > /bin/python3 -I ~/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/python_files/get_output_via_markers.py ~/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/python_files/interpreterInfo.py
2024-08-15 13:58:53.697 [info] Finished searching for interpreters in posix paths locator: 52 milliseconds
2024-08-15 13:58:53.697 [info] > /usr/bin/python3 -I ~/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/python_files/get_output_via_markers.py ~/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/python_files/interpreterInfo.py
2024-08-15 13:58:53.698 [info] Environments refresh paths discovered (event): 55 milliseconds
2024-08-15 13:58:53.698 [info] Environments refresh paths discovered: 55 milliseconds
2024-08-15 13:58:53.767 [info] > /usr/local/bin/python -I ~/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/python_files/get_output_via_markers.py ~/.local/share/code-server/extensions/ms-python.python-2024.12.2-universal/python_files/interpreterInfo.py
2024-08-15 13:58:53.821 [info] Environments refresh finished (event): 178 milliseconds
2024-08-15 13:58:53.826 [info] Environment refresh took 182 milliseconds
2024-08-15 13:58:53.826 [warning] could not find a pixi interpreter for the interpreter at /usr/local/bin/python
2024-08-15 13:58:53.827 [info] Python interpreter path: /usr/local/bin/python
2024-08-15 13:58:55.174 [warning] Shell integration may not be active, environment activated may be overridden by the shell.
2024-08-15 13:58:55.174 [warning] could not find a pixi interpreter for the interpreter at /usr/local/bin/python
